# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
  pull_request:

jobs:
  
  build_python_3_8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          cd api
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Enforce Python code style
        run: cd api && pylint *.py
      - name: Add copy of model
        run: cd api && python get_model.py
      - name: Run unit tests
        run: cd api && pytest

  build_javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Javascript client dependencies
        run: cd client && npm i
      - name: Enforce Javascript code style
        run: |
          cd client
          npm run lint
          npm run format
